# remove codecov comments for pull requests
comment: off

# remove code from analysis
ignore:
# ui code that cannot be tested in intellij
- "src/main/java/com/dubreuia/ui/"
# intellij inspections that we copy in code
- "src/main/java/com/intellij/"
# intellij inspections that we copy in code
- "src/main/java/com/siyeh/"

